language: objective-c
osx_image: xcode8.0
xcode_project: ./WASKit.xcodeproj
xcode_sdk: iphonesimulator10

before_install:
- rm -rf /Users/travis/Library/Developer/Xcode/DerivedData/WASKit-*/
- rvm use $RVM_RUBY_VERSION

install:
- bundle
- bundle install --without=documentation --path ../travis_bundle_dir

script:
- xcodebuild -scheme WASKit -destination "platform=iOS Simulator,name=iPhone 6s,OS=10.0" clean test | xcpretty

after_success: 
  - slather
  - bash <(curl -s https://codecov.io/bash) -f ./_files/CI/TestsReports/cobertura.xml